#!/usr/bin/env python3
"""Write content's clan chat tab (clan_chat/interfaces/clanchat.if) and Clan Setup window (clan_setup.if)
as 474's (474 interfaces 589 and 590).

    python tools/models/genclan474.py "caches/474 cache"

THE TAB is 589: "Clan Chat" centred at the top, "Talking in" and "Owner" in orange, the member list
on a dark translucent panel inside a thin stone border (sprites 962-975), and two bordered buttons,
Join Chat and Clan Setup, whose border 474 drew with client script 92 (four 9x9 corners, 913-916, and
four edges, 917-920) - written out here as the components that script made. Its changing parts are
the CLIENT's, as they were: client codes 1001 talking, 1002 owner, 1003 Join/Leave (the button and its
label), 1005 the list, 1101-1200 member names (Kick), 1201-1300 their worlds - Client.updateClanContent
in Client-Java. 474's LootShare toggle is left out; this game has no LootShare.

THE WINDOW is 590: a stone panel (sprite 297) in its own border, "Clan Chat Setup", and one bordered
box per setting (script 93: the stone and the same border) with its question in orange and its answer
in white. 474 changed an answer from a right-click menu of every rank; a component here has one option,
so a click steps through the ranks this game has (clan_chat/scripts/clan_chat.rs2), and the hint under
the boxes says so. 474's right-hand panel listed your friends with the rank you had given each; ranks
between member and owner are not in this game yet, so the panel is there and says that instead.
LootShare's box is left out with its toggle.

Names the scripts use are kept: clanchat:setup, clan_setup:name / enter / talk / kick and their
*_value texts, clan_setup:close.
"""
import os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
CONTENT = os.path.join(ROOT, 'content')
OUT = os.path.join(CONTENT, 'scripts', 'clan_chat', 'interfaces')

MAX_MEMBERS = 100
ROW = 15


class If:
    def __init__(self, conv, head):
        self.conv = conv
        self.lines = list(head)
        self.fake = 10000

    def com(self, name, kv):
        self.lines.append('')
        self.lines.append('[%s]' % name)
        for k, v in kv:
            self.lines.append('%s=%s' % (k, v))

    def cache(self, fid, name):
        """A component as 474 has it, through port474if's converter (tiling, sprite reuse)."""
        self.conv.names[fid] = name
        for n, kv in self.conv.blocks(fid, self.conv.comps[fid]):
            self.com(n, [(k, v) for k, v in kv if not k.startswith('_')])

    def tiled(self, name, sprite, x, y, w, h):
        self.fake += 1
        self.conv.names[self.fake] = name
        c = {'if3': True, 'type': 5, 'parent': None, 'x': x, 'y': y, 'width': w, 'height': h, 'sprite': sprite,
             'tiling': True, 'ops': [], 'name': ''}
        for n, kv in self.conv.blocks(self.fake, c):
            self.com(n, kv)

    def border(self, name, x, y, w, h, fill=None):
        """What 474's scripts 92 and 93 build: an optional tiled fill, four 9x9 corners, four edges."""
        if fill:
            self.tiled('%s_fill' % name, fill, x, y, w, h)
        for i, (sx, sy, sw, sh, sprite) in enumerate([
                (0, 0, 9, 9, 913), (w - 9, 0, 9, 9, 914), (0, h - 9, 9, 9, 915), (w - 9, h - 9, 9, 9, 916),
                (0, 9, 9, h - 18, 917), (9, 0, w - 18, 9, 918), (w - 9, 9, 9, h - 18, 919), (9, h - 9, w - 18, 9, 920)]):
            self.tiled('%s_b%d' % (name, i), sprite, x + sx, y + sy, sw, sh)

    def write(self, name):
        with open(os.path.join(OUT, name + '.if'), 'w', encoding='utf-8', newline='\r\n') as f:
            f.write('\n'.join(self.lines) + '\n')


def colour(c):
    return '0x%06X' % (c & 0xFFFFFF)


def tab(cache):
    from port474if import Converter
    conv = Converter(cache, 589, 'clanchat', {}, {}, 'overlay')
    c = conv.comps
    f = If(conv, ['// 474\'s clan chat tab (474 interface 589), GENERATED by LostCityServer tools/models/genclan474.py -',
                  '// regenerate it rather than editing by hand. Drawn by the client (Client.updateClanContent);',
                  '// Clan Setup is clan_chat/scripts/clan_chat.rs2.',
                  'type=overlay'])
    orange = colour(c[7]['colour'])
    t = c[7]
    f.com('title', [('type', 'text'), ('x', 4), ('y', t['y'] + 1), ('width', 182), ('height', 14), ('center', 'yes'),
                    ('font', 'b12_full'), ('shadowed', 'yes'), ('text', 'Clan Chat'), ('colour', orange)])
    for key, fid, code in (('talking', 0, 1001), ('owner', 1, 1002)):
        t = c[fid]
        f.com(key, [('type', 'text'), ('x', t['x']), ('y', t['y']), ('clientcode', code), ('width', t['width']),
                    ('height', 14), ('font', 'p11_full'), ('shadowed', 'yes'), ('text', t['text']),
                    ('colour', colour(t['colour']))])
    # the dark panel, then the list on it (its scrollbar where 474's is, at x 170), then the border
    bg = c[4]
    f.com('list_bg', [('type', 'rect'), ('x', bg['x']), ('y', bg['y']), ('width', bg['width']), ('height', bg['height']),
                      ('fill', 'yes'), ('colour', colour(bg['colour'])), ('trans', bg['opacity'])])
    lay = c[5]
    f.com('list', [('type', 'layer'), ('x', lay['x']), ('y', lay['y']), ('clientcode', 1005),
                   ('width', c[6]['x'] - lay['x']), ('height', lay['height']), ('scroll', lay['height'] + 1)])
    for i in range(MAX_MEMBERS):
        f.com('name%d' % i, [('layer', 'list'), ('type', 'text'), ('x', 2), ('y', 2 + i * ROW), ('buttontype', 'normal'),
                             ('clientcode', 1101 + i), ('width', 88), ('height', 14), ('font', 'p11_full'),
                             ('shadowed', 'yes'), ('colour', '0xFFFFFF'), ('option', 'Kick')])
        f.com('world%d' % i, [('layer', 'list'), ('type', 'text'), ('x', 92), ('y', 2 + i * ROW),
                              ('clientcode', 1201 + i), ('width', 58), ('height', 14), ('font', 'p11_full'),
                              ('shadowed', 'yes'), ('colour', '0xFFFF00')])
    for fid in range(10, 18):
        f.cache(fid, 'frame%d' % (fid - 10))
    # the buttons: 474's border, a click box over it, and the label
    for key, fid, label_fid in (('join', 2, 8), ('setup', 3, 9)):
        b, lab = c[fid], c[label_fid]
        f.border('%s_border' % key, b['x'], b['y'], b['width'], b['height'])
        kv = [('type', 'rect'), ('x', b['x']), ('y', b['y']), ('buttontype', 'normal')]
        if key == 'join':
            kv.append(('clientcode', 1003))
        kv += [('width', b['width']), ('height', b['height']), ('trans', 255), ('option', lab['text'])]
        f.com(key, kv)
        lkv = [('type', 'text'), ('x', lab['x']), ('y', lab['y'] + (lab['height'] - 12) // 2)]
        if key == 'join':
            lkv.append(('clientcode', 1003))
        lkv += [('width', lab['width']), ('height', 12), ('center', 'yes'), ('font', 'p11_full'), ('shadowed', 'yes'),
                ('text', lab['text']), ('colour', colour(lab['colour']))]
        f.com('%s_label' % key, lkv)
    f.write('clanchat')
    return conv


def window(cache):
    from port474if import Converter
    conv = Converter(cache, 590, 'clan_setup', {}, {}, 'layer')
    c = conv.comps
    f = If(conv, ['// 474\'s Clan Chat Setup (474 interface 590), GENERATED by LostCityServer tools/models/genclan474.py -',
                  '// regenerate it rather than editing by hand. Scripts: clan_chat/scripts/clan_chat.rs2 (the',
                  '// values come from the engine\'s clan_name / clan_rank).'])
    shade = c[0]
    f.com('shade', [('type', 'rect'), ('x', shade['x']), ('y', shade['y']), ('width', shade['width']),
                    ('height', shade['height']), ('fill', 'yes'), ('colour', '0x000000'), ('trans', shade['opacity'])])
    for fid in range(1, 16):
        f.cache(fid, 'frame%d' % fid)
    close = c[16]
    f.com('close', [('type', 'graphic'), ('x', close['x']), ('y', close['y']), ('buttontype', 'close'), ('width', 16),
                    ('height', 16), ('graphic', conv.sprite(close['sprite']))])
    t = c[17]
    orange = colour(t['colour'])
    f.com('title', [('type', 'text'), ('x', t['x']), ('y', t['y'] + 1), ('width', t['width']), ('height', 14),
                    ('center', 'yes'), ('font', 'b12_full'), ('shadowed', 'yes'), ('text', t['text']), ('colour', orange)])
    # the right-hand panel: 474's friends-and-ranks list, which this game has no ranks for yet
    p = c[18]
    f.com('ranks_bg', [('type', 'rect'), ('x', p['x']), ('y', p['y']), ('width', p['width']), ('height', p['height']),
                       ('fill', 'yes'), ('colour', colour(p['colour'])), ('trans', p['opacity'])])
    o = c[21]
    f.com('ranks_outline', [('type', 'rect'), ('x', o['x']), ('y', o['y']), ('width', o['width']), ('height', o['height']),
                            ('colour', colour(o['colour']))])
    h = c[22]
    f.com('ranks_head', [('type', 'rect'), ('x', h['x']), ('y', h['y']), ('width', h['width']), ('height', h['height']),
                         ('colour', colour(o['colour']))])
    ln = c[23]
    # only as far as the header: with no rows under it, a full-height line would cut the note in two
    f.com('ranks_divider', [('type', 'rect'), ('x', ln['x']), ('y', ln['y']), ('width', 1), ('height', h['height']),
                            ('fill', 'yes'), ('colour', colour(ln['colour']))])
    for key, fid in (('ranks_name', 24), ('ranks_rank', 25)):
        t = c[fid]
        f.com(key, [('type', 'text'), ('x', t['x'] + 3), ('y', t['y'] + 2), ('width', t['width']), ('height', 14),
                    ('font', 'b12_full'), ('shadowed', 'yes'), ('text', t['text']), ('colour', orange)])
    t = c[26]
    f.com('ranks_title', [('type', 'text'), ('x', t['x']), ('y', t['y'] + 3), ('width', t['width']), ('height', 14),
                          ('center', 'yes'), ('font', 'b12_full'), ('shadowed', 'yes'), ('text', t['text']), ('colour', orange)])
    f.com('ranks_none', [('type', 'text'), ('x', p['x']), ('y', p['y'] + 90), ('width', p['width']), ('height', 30),
                         ('center', 'yes'), ('font', 'p11_full'), ('shadowed', 'yes'),
                         ('text', 'Clan ranks are not available yet:\\nfriends can enter, talk or kick\\nas the settings say.'),
                         ('colour', '0xFFFFFF')])
    # the four settings: 474's bordered box, the question over the answer, and a click box over it all
    rows = [('name', 27, 32, 37, 'Set prefix'), ('enter', 28, 33, 38, 'Change'), ('talk', 29, 34, 39, 'Change'),
            ('kick', 30, 35, 40, 'Change')]
    for key, box_fid, value_fid, label_fid, verb in rows:
        b, v, lab = c[box_fid], c[value_fid], c[label_fid]
        f.border('%s_box' % key, b['x'], b['y'], b['width'], b['height'], fill=297)
        f.com('%s_label' % key, [('type', 'text'), ('x', lab['x']), ('y', b['y'] + 7), ('width', lab['width']),
                                 ('height', 12), ('center', 'yes'), ('font', 'p11_full'), ('shadowed', 'yes'),
                                 ('text', lab['text']), ('colour', colour(lab['colour']))])
        f.com('%s_value' % key, [('type', 'text'), ('x', v['x']), ('y', b['y'] + 21), ('width', v['width']),
                                 ('height', 14), ('center', 'yes'), ('font', 'b12_full'), ('shadowed', 'yes'),
                                 ('text', v['text']), ('colour', '0xFFFFFF')])
        f.com(key, [('type', 'rect'), ('x', b['x']), ('y', b['y']), ('buttontype', 'normal'), ('width', b['width']),
                    ('height', b['height']), ('trans', 255), ('option', verb)])
    t = c[42]
    f.com('hint', [('type', 'text'), ('x', t['x']), ('y', c[31]['y'] + 8), ('width', t['width']), ('height', 26),
                   ('center', 'yes'), ('font', 'p11_full'), ('shadowed', 'yes'),
                   ('text', 'Click on white text to\\nchange options.'), ('colour', colour(t['colour']))])
    f.write('clan_setup')
    return conv


def main():
    from if3_474 import Cache
    cache = Cache(sys.argv[1])
    new = []
    for conv in (tab(cache), window(cache)):
        new += conv.write_sprites(os.path.join(CONTENT, 'sprites'))
    print('wrote clanchat.if and clan_setup.if; sprites new: %s' % (' '.join(new) or '-'))
    subprocess.check_call([sys.executable, os.path.join(CONTENT, 'tools', 'ifids.py'), 'clanchat', 'clan_setup'])


if __name__ == '__main__':
    main()
