#!/usr/bin/env python3
"""Write the Enchant Crossbow Bolt window (skill_magic/interfaces/enchant_bolts.if) from 474's (474
interface 432), and bring its bolt picture with it.

    python tools/models/genenchantbolts474.py "caches/474 cache"

474's window is an old-format interface, so port474if.py converts it field for field: ten bolt
buttons in 474's grid, each with its bolt's name lit when you carry some, its Magic level lit when you
have it, and the runes it costs with a count that goes green when you carry enough - staves and
combination runes counted as the spellbook counts them. What the converter cannot know is named here:

  the buttons     opal, jade, pearl, topaz, sapphire, emerald, ruby, diamond, dragon, onyx - the
                  names skill_magic/scripts/spells/enchant_bolts.rs2's triggers use; close is 474's X
  the links       474's inventory (interface 149) and worn equipment (387:28), which its client
                  scripts count from, are this build's inventory:inv and wornitems:worn
  the items       the eight bolts 474 added (9335-9342) by the names they were imported under, and
                  474's two steam staves by this build's
  the models      each rune by this build's model of the same number, and the bolt picture (474
                  model 16871, which is not this build's 16871) imported as obj_enchantbolts474
"""
import os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
CONTENT = os.path.join(ROOT, 'content')
OUT = os.path.join(CONTENT, 'scripts', 'skill_magic', 'interfaces', 'enchant_bolts.if')

NAMES = {93: 'opal', 98: 'jade', 103: 'pearl', 107: 'topaz', 111: 'sapphire', 115: 'emerald', 119: 'ruby',
         123: 'diamond', 127: 'dragon', 131: 'onyx', 189: 'close'}
LINKS = {149 << 16: 'inventory:inv', (387 << 16) | 28: 'wornitems:worn'}
OBJS = {9335: 'jade_bolts', 9336: 'topaz_bolts', 9337: 'sapphire_bolts', 9338: 'emerald_bolts', 9339: 'ruby_bolts',
        9340: 'diamond_bolts', 9341: 'dragon_bolts', 9342: 'onyx_bolts', 11736: 'steam_battlestaff',
        11738: 'mystic_steam_staff'}
BOLT_MODEL = 16871
BOLT_MODEL_NAME = 'obj_enchantbolts474'


def register_model(name):
    pack = os.path.join(CONTENT, 'pack', 'model.pack')
    text = open(pack, newline='').read()
    nl = '\r\n' if '\r\n' in text else '\n'
    if re.search(r'(?m)^\d+=%s\r?$' % re.escape(name), text):
        return
    nxt = max(int(i) for i in re.findall(r'(?m)^(\d+)=', text)) + 1
    with open(pack, 'w', newline='') as f:
        f.write(text.rstrip('\r\n') + nl + '%d=%s' % (nxt, name) + nl)


def main():
    from if3_474 import Cache
    from port474if import Converter, load_pack
    cache = Cache(sys.argv[1])
    conv = Converter(cache, 432, 'enchant_bolts', NAMES, LINKS, 'layer')
    conv.objs.update(OBJS)
    text = conv.convert()

    # the bolt picture, byte for byte (474 kept the old model format for it)
    data = cache.store.read(7, BOLT_MODEL)
    assert data[-2:] != b'\xff\xff', 'bolt model is new-format'
    open(os.path.join(CONTENT, 'models', 'obj', BOLT_MODEL_NAME + '.ob2'), 'wb').write(data)
    register_model(BOLT_MODEL_NAME)

    # every model component by name: the runes are this build's models of the same number
    models = load_pack('model')
    for fid, c in conv.comps.items():
        if c.get('type') != 6 or not c.get('model'):
            continue
        name = BOLT_MODEL_NAME if c['model'] == BOLT_MODEL else models.get(c['model'])
        if not name:
            raise SystemExit('474 model %d has no content name' % c['model'])
        comp = conv.name(fid)
        text = re.sub(r'(?m)^(\[%s\]\ntype=model\n)' % re.escape(comp), r'\1model=%s\n' % name, text)

    head = ['// 474\'s Enchant Crossbow Bolt window (474 interface 432), GENERATED by LostCityServer',
            '// tools/models/genenchantbolts474.py - regenerate it rather than editing by hand.',
            '// Scripts: skill_magic/scripts/spells/enchant_bolts.rs2.']
    with open(OUT, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write('\n'.join(head) + '\n' + text)
    new = conv.write_sprites(os.path.join(CONTENT, 'sprites'))
    for note in conv.notes:
        if 'model' not in note:
            print('  note:', note)
    print('wrote %s; sprites new: %s' % (OUT, ' '.join(new) or '-'))
    # the rune pouch counts too, as it does in every window that counts runes (content's generator)
    subprocess.check_call([sys.executable, os.path.join(CONTENT, 'tools', 'genpouchruneops.py')], cwd=CONTENT)
    subprocess.check_call([sys.executable, os.path.join(CONTENT, 'tools', 'ifids.py'), 'enchant_bolts'])


if __name__ == '__main__':
    main()
