#!/usr/bin/env python3
"""Write content's quest list (scripts/interfaces/questlist.if) as 474's (474 interface 274).

    python tools/models/genquest474.py "caches/474 cache"

474's quest tab is a new-format interface: "Quest Points: N" across the top, a steel frame over a
darkened panel, and one scrolling list - "Free Quests", every free quest, "Members' Quests", every
members' quest, each list alphabetical with a leading "The" ignored - that a client script laid out
and coloured. This writes the same tab in the old format:

  the frame     474's components 1-9 as they are (port474if.Converter, so the steel border is the
                content's own steelborder art where 474 reused it), the dark fill first so the list
                draws over it
  qp            the title, Quest Points from %qp
  com_0         the scrolling list, where 474 had it. Its children keep the content's names - every
                quest row is named for its quest (questlist:cook), and ~update_questlist and 600-odd
                ~send_quest_progress calls colour and wire them by those names - so the rows are
                re-laid, not replaced: 474's font, 15 pixels apart, in 474's order, the free ones
                above com_43 as the 377 list had them.

tools/genbosskills.py (in content) appends its "Boss kill counts" row under the last one; this reruns
it afterwards so the row follows the new list.
"""
import os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
CONTENT = os.path.join(ROOT, 'content')
PATH = os.path.join(CONTENT, 'scripts', 'interfaces', 'questlist.if')
BOSS_ROW = 'boss_kills'   # genbosskills.py's, which it puts back itself


def parse_if(text):
    out = []
    for part in re.split(r'\n(?=\[)', text.replace('\r\n', '\n')):
        lines = [l for l in part.split('\n') if l.strip() and not l.startswith('//')]
        if lines and lines[0].startswith('['):
            out.append((lines[0][1:-1], dict(l.split('=', 1) for l in lines[1:] if '=' in l)))
    return out


def sort_key(title):
    t = title.lower()
    return t[4:] if t.startswith('the ') else t


def main():
    from if3_474 import Cache
    from port474if import Converter
    cache = Cache(sys.argv[1])
    comps = cache.load(274)
    conv = Converter(cache, 274, 'questlist', {}, {}, 'overlay')

    old = parse_if(open(PATH, encoding='utf-8').read())
    by = dict(old)
    members_y = int(by['com_43']['y'])
    rows = [(n, d) for n, d in old if d.get('layer') == 'com_0' and 'buttontype' in d and n != BOSS_ROW]
    free = sorted([r for r in rows if int(r[1]['y']) < members_y], key=lambda r: sort_key(r[1]['text']))
    members = sorted([r for r in rows if int(r[1]['y']) > members_y], key=lambda r: sort_key(r[1]['text']))

    out = ['// 474\'s quest list (474 interface 274), GENERATED by LostCityServer tools/models/genquest474.py -',
           '// regenerate it rather than editing by hand. The rows are the content\'s, by name.']

    def com(name, kv):
        if out[-1] != out[1]:
            out.append('')
        out.append('[%s]' % name)
        out.extend('%s=%s' % (k, v) for k, v in kv)

    # the list, first, and with its scroll line in its first block - genbosskills.py grows that line
    lay = comps[0]
    head, rest = [], []
    y = comps[13]['y']
    head.append(('com_24', [('layer', 'com_0'), ('type', 'text'), ('x', comps[13]['x']), ('y', y), ('width', 152),
                            ('height', 15), ('font', 'b12_full'), ('shadowed', 'yes'), ('text', 'Free Quests'),
                            ('colour', '0x%06X' % comps[13]['colour'])]))
    y += 18

    def row(n, d, y):
        kv = [('layer', 'com_0'), ('type', 'text'), ('x', comps[14]['x']), ('y', y), ('buttontype', 'normal'),
              ('width', 152), ('height', 15), ('font', 'p11_full'), ('shadowed', 'yes'), ('text', d['text']),
              ('colour', d.get('colour', '0xFF0000')), ('overcolour', '0xFFFFFF'),
              ('option', 'Read Journal @lre@%s' % d['text'])]
        return (n, kv)

    for n, d in free:
        rest.append(row(n, d, y))
        y += 15
    y += 5
    rest.append(('com_43', [('layer', 'com_0'), ('type', 'text'), ('x', comps[32]['x']), ('y', y), ('width', 152),
                            ('height', 15), ('font', 'b12_full'), ('shadowed', 'yes'), ('text', "Members' Quests"),
                            ('colour', '0x%06X' % comps[32]['colour'])]))
    y += 18
    for n, d in members:
        rest.append(row(n, d, y))
        y += 15

    com('com_0', [('type', 'layer'), ('x', lay['x']), ('y', lay['y']), ('width', lay['width']),
                  ('height', lay['height']), ('scroll', y + 6)])
    # the dark fill under the list, then the list, then the steel frame over its edges
    fill = conv.blocks(1, comps[1])
    for name, kv in fill:
        # the new format's transparency is the old one's trans: 0 opaque, 255 invisible
        kv = [(k, v) for k, v in kv if k not in ('layer', 'trans')] + [('trans', comps[1]['opacity'])]
        com('frame_fill', kv)
    for name, kv in head + rest:
        com(name, kv)
    k = 0
    for fid in range(2, 10):
        for name, kv in conv.blocks(fid, comps[fid]):
            com('frame%d' % k, kv)
            k += 1
    t = comps[10]
    com('qp', [('type', 'text'), ('x', t['x']), ('y', t['y']), ('width', t['width']), ('height', t['height']),
               ('script1op1', 'pushvar,qp'), ('font', 'b12_full'), ('shadowed', 'yes'), ('text', 'Quest Points: %1'),
               ('colour', '0x%06X' % t['colour'])])

    with open(PATH, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write('\n'.join(out) + '\n')
    new = conv.write_sprites(os.path.join(CONTENT, 'sprites'))
    print('wrote %s: %d free, %d members; sprites new: %s' % (PATH, len(free), len(members), ' '.join(new) or '-'))
    subprocess.check_call([sys.executable, os.path.join(CONTENT, 'tools', 'genbosskills.py')], cwd=CONTENT)
    subprocess.check_call([sys.executable, os.path.join(CONTENT, 'tools', 'ifids.py'), 'questlist'])


if __name__ == '__main__':
    main()
