#!/usr/bin/env python3
"""Write content's quest list (scripts/interfaces/questlist.if) as 474's (474 interface 274).

    python tools/models/genquest474.py "caches/474 cache" [--content=<content checkout>]

474's quest tab is a new-format interface: "Quest Points: N" across the top, a steel frame over a
darkened panel, and one scrolling list - "Free Quests", every free quest, "Members' Quests", every
members' quest, each list alphabetical with a leading "The" ignored - that a client script laid out
and coloured. This writes the same tab in the old format:

  the frame     474's components 1-9 as they are (port474if.Converter, so the steel border is the
                content's own steelborder art where 474 reused it), the dark fill first so the list
                draws over it
  qp            the title, Quest Points from %qp
  com_0         the scrolling list, where 474 had it. Its children keep the content's names - every
                quest row is named for its quest (questlist:cook), and ~update_questlist and 600-odd
                ~send_quest_progress calls colour and wire them by those names - so the rows are
                re-laid, not replaced: 474's font, 15 pixels apart, in 474's order, the free ones
                above com_43 as the 377 list had them.

tools/genbosskills.py (in content) appends its "Boss kill counts" row under the last one and
tools/gencollectionlog.py its "Collection log" row under that; this reruns both afterwards so the
rows follow the new list.

THE QUEST TAB'S BUTTON ROW. The quest list is one of the quest tab's five pages (content's
tools/genquesttab.py has the rest), so the whole of 474's tab is moved down under the row of page
buttons: the title to where every page has its title, and the framed list to the band every page's
body uses. Edges in the top half of 474's list move down by TOP, edges in the bottom half by
TOP - SHRINK, so the steel frame's corners keep their size and its sides get shorter. The button row
itself is genquesttab.py's own block in this file, which it puts back itself when this reruns it.

    python tools/models/genquest474.py "caches/474 cache" [--content=<content checkout>]
"""
import os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
CONTENT = os.path.join(ROOT, 'content')
for _a in sys.argv[1:]:
    if _a.startswith('--content='):
        CONTENT = os.path.abspath(_a.split('=', 1)[1])
PATH = os.path.join(CONTENT, 'scripts', 'interfaces', 'questlist.if')
BOSS_ROW = 'boss_kills'   # genbosskills.py's, which it puts back itself
# gencollectionlog.py's, likewise - left in, it was read back as a members' quest and sorted in
OWN_ROWS = (BOSS_ROW, 'collection_log')


def quest_tab_layout():
    """The quest tab's shared geometry, from content's genquesttab.py."""
    sys.path.insert(0, os.path.join(CONTENT, 'tools'))
    import genquesttab
    return genquesttab


def fit(c, top, shrink, mid):
    """Move one of 474's components into the band under the page buttons (see the docstring)."""
    y0, y1 = c['y'], c['y'] + c['height']
    y0 += top if y0 < mid else top - shrink
    y1 += top if y1 < mid else top - shrink
    return dict(c, y=y0, height=y1 - y0)


def parse_if(text):
    out = []
    for part in re.split(r'\n(?=\[)', text.replace('\r\n', '\n')):
        lines = [l for l in part.split('\n') if l.strip() and not l.startswith('//')]
        if lines and lines[0].startswith('['):
            out.append((lines[0][1:-1], dict(l.split('=', 1) for l in lines[1:] if '=' in l)))
    return out


def sort_key(title):
    t = title.lower()
    return t[4:] if t.startswith('the ') else t


def main():
    from if3_474 import Cache
    from port474if import Converter
    args = [a for a in sys.argv[1:] if not a.startswith('--content=')]
    cache = Cache(args[0])
    comps = cache.load(274)
    conv = Converter(cache, 274, 'questlist', {}, {}, 'overlay')

    # 474's list spans 24..250; the page body is BODY_TOP..BODY_BOTTOM
    qt = quest_tab_layout()
    lay0 = comps[0]
    top = qt.BODY_TOP - lay0['y']
    shrink = lay0['height'] - (qt.BODY_BOTTOM - qt.BODY_TOP)
    mid = lay0['y'] + lay0['height'] // 2
    for fid in range(0, 10):
        comps[fid] = fit(comps[fid], top, shrink, mid)

    old = parse_if(open(PATH, encoding='utf-8').read())
    by = dict(old)
    members_y = int(by['com_43']['y'])
    rows = [(n, d) for n, d in old if d.get('layer') == 'com_0' and 'buttontype' in d and n not in OWN_ROWS]
    free = sorted([r for r in rows if int(r[1]['y']) < members_y], key=lambda r: sort_key(r[1]['text']))
    members = sorted([r for r in rows if int(r[1]['y']) > members_y], key=lambda r: sort_key(r[1]['text']))

    out = ['// 474\'s quest list (474 interface 274), GENERATED by LostCityServer tools/models/genquest474.py -',
           '// regenerate it rather than editing by hand. The rows are the content\'s, by name.']

    def com(name, kv):
        if out[-1] != out[1]:
            out.append('')
        out.append('[%s]' % name)
        out.extend('%s=%s' % (k, v) for k, v in kv)

    # the list, first, and with its scroll line in its first block - genbosskills.py grows that line
    lay = comps[0]
    head, rest = [], []
    y = comps[13]['y']
    head.append(('com_24', [('layer', 'com_0'), ('type', 'text'), ('x', comps[13]['x']), ('y', y), ('width', 152),
                            ('height', 15), ('font', 'b12_full'), ('shadowed', 'yes'), ('text', 'Free Quests'),
                            ('colour', '0x%06X' % comps[13]['colour'])]))
    y += 18

    def row(n, d, y):
        kv = [('layer', 'com_0'), ('type', 'text'), ('x', comps[14]['x']), ('y', y), ('buttontype', 'normal'),
              ('width', 152), ('height', 15), ('font', 'p11_full'), ('shadowed', 'yes'), ('text', d['text']),
              ('colour', d.get('colour', '0xFF0000')), ('overcolour', '0xFFFFFF'),
              ('option', 'Read Journal @lre@%s' % d['text'])]
        return (n, kv)

    for n, d in free:
        rest.append(row(n, d, y))
        y += 15
    y += 5
    rest.append(('com_43', [('layer', 'com_0'), ('type', 'text'), ('x', comps[32]['x']), ('y', y), ('width', 152),
                            ('height', 15), ('font', 'b12_full'), ('shadowed', 'yes'), ('text', "Members' Quests"),
                            ('colour', '0x%06X' % comps[32]['colour'])]))
    y += 18
    for n, d in members:
        rest.append(row(n, d, y))
        y += 15

    com('com_0', [('type', 'layer'), ('x', lay['x']), ('y', lay['y']), ('width', lay['width']),
                  ('height', lay['height']), ('scroll', y + 6)])
    # the dark fill under the list, then the list, then the steel frame over its edges
    fill = conv.blocks(1, comps[1])
    for name, kv in fill:
        # the new format's transparency is the old one's trans: 0 opaque, 255 invisible
        kv = [(k, v) for k, v in kv if k not in ('layer', 'trans')] + [('trans', comps[1]['opacity'])]
        com('frame_fill', kv)
    for name, kv in head + rest:
        com(name, kv)
    k = 0
    for fid in range(2, 10):
        for name, kv in conv.blocks(fid, comps[fid]):
            com('frame%d' % k, kv)
            k += 1
    # the title where every page of the quest tab has its title
    t = dict(comps[10], x=qt.TITLE_X, y=qt.TITLE_Y, width=qt.TITLE_W, height=qt.TITLE_H)
    com('qp', [('type', 'text'), ('x', t['x']), ('y', t['y']), ('width', t['width']), ('height', t['height']),
               ('script1op1', 'pushvar,qp'), ('font', 'b12_full'), ('shadowed', 'yes'), ('text', 'Quest Points: %1'),
               ('colour', '0x%06X' % t['colour'])])

    # The other generators' rows are carried over as they were, for them to put back in place: were
    # they dropped here, the first of the tools below to sync questlist's interface ids would free
    # their ids, and the rows would come back under new numbers on every run.
    old_text = open(PATH, encoding='utf-8').read().replace('\r\n', '\n')
    marks = [i for i in (old_text.find('// APPENDED by tools/gencollectionlog.py'),
                         old_text.find('// APPENDED by tools/genbosskills.py')) if i >= 0]
    tail = old_text[min(marks):].rstrip('\n') if marks else ''
    with open(PATH, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write('\n'.join(out) + '\n' + ('\n' + tail + '\n' if tail else ''))
    new = conv.write_sprites(os.path.join(CONTENT, 'sprites'))
    print('wrote %s: %d free, %d members; sprites new: %s' % (PATH, len(free), len(members), ' '.join(new) or '-'))
    # the button row first: gencollectionlog.py syncs questlist's interface ids, and would drop the
    # row's ids if the row were not back in the file yet
    for tool in ('genquesttab.py', 'genbosskills.py', 'gencollectionlog.py'):
        subprocess.check_call([sys.executable, os.path.join(CONTENT, 'tools', tool)], cwd=CONTENT)
    subprocess.check_call([sys.executable, os.path.join(CONTENT, 'tools', 'ifids.py'), 'questlist'], cwd=CONTENT)


if __name__ == '__main__':
    main()
