#!/usr/bin/env python3
"""Write the anvil's Smithing window (skill_smithing/interfaces/smithing.if) from 474's (474 interface
312), which has room for the crossbow parts the 377 one did not.

    python tools/models/gensmithing474.py "caches/474 cache"

474's window is the 377 one grown a column: the same five columns of items with their names and bar
counts, lit by the same two varps (210 smithbars, 211 modified_smith - this build numbers them the
same), plus a sixth for unfinished bolts and crossbow limbs. It is an old-format interface, so
port474if.py converts it field for field. What the converter cannot know is named here - the names
skill_smithing/scripts/smithing/smithing.rs2 uses:

  column1-5       the five item columns, as before; column_bolts is the new one
  column_claws    the claws under the axes (Death Plateau), in claws_layer
  other_layer     the fourth row of the last column - wire, a spit or studs - titled by other_text
  stud_layer      the steel studs row
  lantern_layer   the iron oil lantern frame, which this build has no recipe for and keeps hidden
  grapple_layer   the mithril grapple tip, which this build does not have; hidden
  close           474's X: the lit one shows while you hover the plain one, and either closes
"""
import os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
CONTENT = os.path.join(ROOT, 'content')
OUT = os.path.join(CONTENT, 'scripts', 'skill_smithing', 'interfaces', 'smithing.if')

NAMES = {146: 'column1', 147: 'column2', 148: 'column3', 149: 'column4', 150: 'column5', 151: 'column_bolts',
         166: 'column_claws', 170: 'column_lantern', 180: 'column_grapple', 124: 'other_layer', 123: 'other_text',
         161: 'stud_layer', 167: 'claws_layer', 168: 'lantern_layer', 174: 'bolts_layer', 179: 'grapple_layer',
         185: 'close_layer', 184: 'close'}
HIDDEN = ('lantern_layer', 'grapple_layer')


def main():
    from if3_474 import Cache
    from port474if import Converter
    cache = Cache(sys.argv[1])
    conv = Converter(cache, 312, 'smithing', NAMES, {}, 'layer')
    text = conv.convert()
    # the item columns hold five (474's are sixty tall, which draws the same)
    for col in ('column1', 'column2', 'column3', 'column4', 'column5'):
        head, sep, rest = text.partition('[%s]\n' % col)
        block, nxt, tail = rest.partition('\n\n')
        block = block.replace('height=60', 'height=5')
        text = head + sep + block + nxt + tail
    for layer in HIDDEN:
        head, sep, rest = text.partition('[%s]\n' % layer)
        block, nxt, tail = rest.partition('\n\n')
        if 'hide=yes' not in block:
            block += '\nhide=yes'
        text = head + sep + block + nxt + tail

    head = ['// 474\'s Smithing window (474 interface 312), GENERATED by LostCityServer',
            '// tools/models/gensmithing474.py - regenerate it rather than editing by hand.',
            '// Scripts: skill_smithing/scripts/smithing/smithing.rs2.']
    with open(OUT, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write('\n'.join(head) + '\n' + text)
    new = conv.write_sprites(os.path.join(CONTENT, 'sprites'))
    for note in conv.notes:
        print('  note:', note)
    print('wrote %s; sprites new: %s' % (OUT, ' '.join(new) or '-'))
    subprocess.check_call([sys.executable, os.path.join(CONTENT, 'tools', 'ifids.py'), 'smithing'])


if __name__ == '__main__':
    main()
