#!/usr/bin/env python3
"""Generate osrstexhsl.py: the average colour of every OSRS texture, as a 377 HSL16.

WHY THIS EXISTS. A textured OSRS face carries no usable colour of its own - the colour
field holds the texture id. When 377 has no equivalent texture the face has to be painted
flat, and osrs2ob2.py used to paint every one of them the same orange-brown
(TEXTURED_HSL 6070). That is fine for a plank and badly wrong for pine needles.

The cache already has the right answer. Bytes 3-4 of each texture record in index 9 are a
377-style HSL16 of that texture's own average colour, so a flattened face can be given the
colour of the texture it should have had, for free, with no image decoding at import time.

Proven rather than assumed: decode the sprite each record points at (index 8), average its
non-transparent pixels, convert the record's HSL16 back to RGB and compare. Median distance
across all 214 textures is 6 out of 255, against 92 for random pairs of textures.

That check passes whether or not the records are keyed correctly, because it compares each
record against ITS OWN sprite - which is why it never caught the off-by-one this function
used to have. See read_records.

    python3 tools/models/gentexhsl.py "<osrs cache>" > tools/models/osrstexhsl.py
"""
import sys, os, struct, datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from flatcache import Store

TEXTURE_INDEX = 9       # OSRS texture definitions: one group, one file per texture
RECORD = 7              # spriteId g2, averageHsl g2, isTransparent g1, animDir g1, animSpeed g1


def read_records(st):
    """Split index 9 group 0 into its per-texture files. Refuses anything that does not
    split exactly: every record in this cache is 7 bytes, and a short or long one means the
    format moved and the rest of this script's assumptions are void."""
    d = st.read(TEXTURE_INDEX, 0)
    if not d:
        raise SystemExit('cache has no texture index')
    n = len(st.reftable(TEXTURE_INDEX).file_ids[0])
    chunks = d[-1]
    p = len(d) - 1 - chunks * n * 4
    if p < 0:
        raise SystemExit('texture group trailer does not fit')
    sizes = [0] * n
    for _ in range(chunks):
        delta = 0
        for f in range(n):
            delta += struct.unpack('>i', d[p:p + 4])[0]; p += 4
            sizes[f] += delta
    if sum(sizes) != len(d) - 1 - chunks * n * 4:
        raise SystemExit('texture file sizes do not account for the group')
    if set(sizes) != {RECORD}:
        raise SystemExit(f'expected {RECORD}-byte texture records, got sizes {sorted(set(sizes))}')
    # KEYED BY FILE ID, NOT BY POSITION, which is the whole point of this rewrite: the index has
    # 214 files whose ids run 0 to 214 with id 54 MISSING, so a list indexed by position is off by
    # one from 55 up. That is how texture 59 - the Infernal cape's molten crust - was read as
    # texture 60's jungle leaves, and why the cape shipped with an olive-green stripe down it. The
    # 31 textures 377 shares are all id <= 49, below the gap, which is the only reason nothing
    # else in this fork was affected.
    ids = st.reftable(TEXTURE_INDEX).file_ids[0]
    if len(ids) != n:
        raise SystemExit('texture index file count does not match its reference table')
    off = 0; out = {}
    for fid, s in zip(ids, sizes):
        r = d[off:off + s]; off += s
        out[fid] = dict(sprite=int.from_bytes(r[0:2], 'big'), hsl=(r[2] << 8) | r[3],
                        transparent=r[4], anim_dir=r[5], anim_speed=r[6])
    return out


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    cache = sys.argv[1]
    recs = read_records(Store(cache))
    w = sys.stdout.write
    w('"""Average colour of every OSRS texture, as a 377 HSL16.\n\n')
    w('GENERATED by tools/models/gentexhsl.py - do not edit by hand.\n')
    w(f'Source: {os.path.basename(os.path.normpath(cache))}, '
      f'{len(recs)} textures, {datetime.date.today().isoformat()}.\n\n')
    w('Used by osrs2ob2.py for textured faces whose texture 377 does not have: the face is\n')
    w('painted with the average colour of the texture it should have carried, instead of one\n')
    w('global stand-in for every texture in the game.\n"""\n\n')
    w('TEXTURE_HSL = {\n')
    for i in sorted(recs):
        r = recs[i]
        w(f'    {i}: {r["hsl"]},'.ljust(20) + f'  # sprite {r["sprite"]}'
          + (f', animated dir {r["anim_dir"]} speed {r["anim_speed"]}' if r['anim_speed'] else '')
          + '\n')
    w('}\n')


if __name__ == '__main__':
    main()
