"""Average colour of every OSRS texture, as a 377 HSL16.

GENERATED by tools/models/gentexhsl.py - do not edit by hand.
Source: newest cache, 214 textures, 2026-09-17.

Used by osrs2ob2.py for textured faces whose texture 377 does not have: the face is
painted with the average colour of the texture it should have carried, instead of one
global stand-in for every texture in the game.
"""

TEXTURE_HSL = {
    0: 5654,          # sprite 447
    1: 39103,         # sprite 448
    2: 6183,          # sprite 449
    3: 4636,          # sprite 450
    4: 6678,          # sprite 451
    5: 6024,          # sprite 452
    6: 2473,          # sprite 453
    7: 7057,          # sprite 454
    8: 12818,         # sprite 455
    9: 5927,          # sprite 456
    10: 8233,         # sprite 530
    11: 5155,         # sprite 457
    12: 18,           # sprite 458
    13: 32847,        # sprite 459
    14: 5295,         # sprite 460
    15: 47161,        # sprite 461
    16: 6934,         # sprite 462
    17: 39640,        # sprite 463, animated dir 1 speed 2
    18: 9534,         # sprite 464
    19: 5405,         # sprite 465
    20: 5662,         # sprite 466
    21: 6673,         # sprite 467
    22: 4512,         # sprite 468
    23: 7446,         # sprite 469
    24: 40269,        # sprite 531, animated dir 1 speed 2
    25: 29101,        # sprite 470
    26: 81,           # sprite 471
    27: 5648,         # sprite 472
    28: 21534,        # sprite 473
    29: 13862,        # sprite 474
    30: 12698,        # sprite 475
    31: 6089,         # sprite 476
    32: 5541,         # sprite 477
    33: 5009,         # sprite 478
    34: 9443,         # sprite 479, animated dir 1 speed 2
    35: 7484,         # sprite 480
    36: 3733,         # sprite 481
    37: 32,           # sprite 482
    38: 6740,         # sprite 483
    39: 13482,        # sprite 484
    40: 6089,         # sprite 485, animated dir 1 speed 2
    41: 10128,        # sprite 486
    42: 8295,         # sprite 532
    43: 10290,        # sprite 487
    44: 41,           # sprite 488
    45: 9256,         # sprite 533
    46: 3119,         # sprite 490
    47: 8403,         # sprite 491
    48: 6434,         # sprite 492
    49: 5592,         # sprite 493
    50: 9380,         # sprite 643
    51: 5679,         # sprite 644
    52: 41072,        # sprite 763
    53: 35049,        # sprite 861
    55: 14483,        # sprite 866
    56: 709,          # sprite 1075, animated dir 1 speed 2
    57: 108,          # sprite 1076, animated dir 1 speed 2
    58: 3747,         # sprite 1396
    59: 3875,         # sprite 318, animated dir 1 speed 1
    60: 12818,        # sprite 1648
    61: 43086,        # sprite 3024
    62: 73,           # sprite 3025
    63: 58,           # sprite 3026
    64: 61,           # sprite 3027
    65: 55339,        # sprite 3028
    66: 55350,        # sprite 3029
    67: 61,           # sprite 3030
    68: 45,           # sprite 3031
    69: 43048,        # sprite 3032
    70: 43038,        # sprite 3033
    71: 66,           # sprite 3034
    72: 43017,        # sprite 3035
    73: 63,           # sprite 3036
    74: 36,           # sprite 3037
    75: 41,           # sprite 3038
    76: 55337,        # sprite 3039
    77: 54,           # sprite 3040
    78: 61,           # sprite 3041
    79: 55355,        # sprite 3042
    80: 32781,        # sprite 3043
    81: 50,           # sprite 3044
    82: 57,           # sprite 3045
    83: 70,           # sprite 3046
    84: 43066,        # sprite 3047
    85: 55346,        # sprite 3048
    86: 55342,        # sprite 3049
    87: 51,           # sprite 3050
    88: 42,           # sprite 3023
    89: 14482,        # sprite 3364
    90: 14482,        # sprite 3365
    91: 38002,        # sprite 3523
    92: 49262,        # sprite 3601
    93: 120,          # sprite 3602
    94: 4133,         # sprite 3603
    95: 32,           # sprite 4377
    96: 8384,         # sprite 1635
    97: 8384,         # sprite 3592
    98: 55738,        # sprite 4664
    99: 55738,        # sprite 4664, animated dir 4 speed 1
    100: 55738,       # sprite 4664, animated dir 4 speed 2
    101: 55738,       # sprite 4664, animated dir 4 speed 3
    102: 55738,       # sprite 4664, animated dir 4 speed 4
    103: 55738,       # sprite 4664, animated dir 4 speed 5
    104: 55606,       # sprite 4665
    105: 55606,       # sprite 4665, animated dir 4 speed 1
    106: 55606,       # sprite 4665, animated dir 4 speed 2
    107: 55606,       # sprite 4665, animated dir 4 speed 3
    108: 55606,       # sprite 4665, animated dir 4 speed 4
    109: 55606,       # sprite 4665, animated dir 4 speed 5
    110: 55606,       # sprite 4666
    111: 55606,       # sprite 4666, animated dir 4 speed 1
    112: 55606,       # sprite 4666, animated dir 4 speed 2
    113: 55606,       # sprite 4666, animated dir 4 speed 3
    114: 55606,       # sprite 4666, animated dir 4 speed 4
    115: 55606,       # sprite 4666, animated dir 4 speed 5
    116: 5405,        # sprite 4667
    117: 6307,        # sprite 4890
    118: 6322,        # sprite 4891
    119: 5147,        # sprite 4923
    120: 7446,        # sprite 5530
    121: 3272,        # sprite 5601
    122: 3272,        # sprite 5602
    123: 11666,       # sprite 5603
    124: 16914,       # sprite 5604
    125: 6303,        # sprite 5605
    126: 6303,        # sprite 5606
    127: 26921,       # sprite 6313
    128: 26921,       # sprite 6314
    129: 14759,       # sprite 6408
    130: 38074,       # sprite 7202
    131: 39094,       # sprite 7203
    132: 40115,       # sprite 7204
    133: 40235,       # sprite 7205
    134: 40231,       # sprite 7206
    135: 36032,       # sprite 7207
    136: 36027,       # sprite 7208
    137: 36022,       # sprite 7209
    138: 38067,       # sprite 7210
    139: 38061,       # sprite 7211
    140: 37042,       # sprite 7212
    141: 37040,       # sprite 7213
    142: 37166,       # sprite 7214
    143: 37164,       # sprite 7215
    144: 37162,       # sprite 7216
    145: 41155,       # sprite 7217
    146: 41150,       # sprite 7218
    147: 42169,       # sprite 7219
    148: 43190,       # sprite 7220
    149: 43311,       # sprite 7221
    150: 40129,       # sprite 7222
    151: 40123,       # sprite 7223
    152: 40118,       # sprite 7224
    153: 41139,       # sprite 7225
    154: 42283,       # sprite 7226
    155: 41152,       # sprite 7227
    156: 41147,       # sprite 7228
    157: 41142,       # sprite 7229
    158: 44210,       # sprite 7230
    159: 44202,       # sprite 7231
    160: 38214,       # sprite 7232
    161: 38081,       # sprite 7233
    162: 38205,       # sprite 7234
    163: 40250,       # sprite 7235
    164: 40242,       # sprite 7236
    165: 38092,       # sprite 7237
    166: 38089,       # sprite 7238
    167: 38085,       # sprite 7239
    168: 40131,       # sprite 7240
    169: 40125,       # sprite 7241
    170: 37193,       # sprite 7242
    171: 37184,       # sprite 7243
    172: 37179,       # sprite 7244
    173: 38198,       # sprite 7245
    174: 38195,       # sprite 7246
    175: 33976,       # sprite 7247
    176: 33971,       # sprite 7248
    177: 33965,       # sprite 7249
    178: 33965,       # sprite 7250
    179: 33958,       # sprite 7251
    180: 37050,       # sprite 7252
    181: 37045,       # sprite 7253
    182: 37168,       # sprite 7254
    183: 37163,       # sprite 7255
    184: 38183,       # sprite 7256
    185: 38067,       # sprite 7257
    186: 38062,       # sprite 7258
    187: 38057,       # sprite 7259
    188: 37158,       # sprite 7260
    189: 37027,       # sprite 7261
    190: 14747,       # sprite 7263
    191: 13849,       # sprite 7264
    192: 8475,        # sprite 7265
    193: 8601,        # sprite 7266
    194: 12581,       # sprite 7267
    195: 12582,       # sprite 7268
    196: 6437,        # sprite 7269
    197: 7462,        # sprite 7270
    198: 10534,       # sprite 7271
    199: 12572,       # sprite 7272
    200: 4262,        # sprite 7273
    201: 7324,        # sprite 7274
    202: 9638,        # sprite 7275
    203: 9638,        # sprite 7276
    204: 5415,        # sprite 7277
    205: 6438,        # sprite 7278
    206: 55775,       # sprite 7279
    207: 38,          # sprite 7280
    208: 41242,       # sprite 7262
    209: 1431,        # sprite 8512
    210: 2456,        # sprite 8513
    211: 9883,        # sprite 8556
    212: 9883,        # sprite 8557
    213: 5778,        # sprite 8558
    214: 5778,        # sprite 8559
}
